import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { WalletProvider } from '@/context/WalletContext';
import Script from 'next/script';
import { FHEVMProvider } from '@/context/FHEVMContext';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'OTC private market',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <title>OTC</title>
        <Script
          src="https://cdn.zama.ai/fhevmjs/0.6.2/fhevmjs.umd.cjs"
          strategy="beforeInteractive"
        />
        <FHEVMProvider>
          <WalletProvider>{children}</WalletProvider>
        </FHEVMProvider>
      </body>
    </html>
  );
}
